version: '3'

services:
  nuxt:
    container_name: nuxt
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/var/www/html
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
